# Generated by Django 3.2.23 on 2025-06-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country_state'), name='unique_city_name_country_state'),
        ),
    ]
