# Generated by Django 3.2.23 on 2025-06-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20250624_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ManyToManyField(related_name='addresses', to='addresses.City', verbose_name='City'),
        ),
    ]
