# Generated by Django 3.2.23 on 2025-06-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20250624_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='cities',
            field=models.ManyToManyField(related_name='addresses', to='addresses.City', verbose_name='City'),
        ),
    ]
