# Generated by Django 3.2.23 on 2025-06-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truckstop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('opis', models.PositiveIntegerField(verbose_name='OPIS')),
                ('rack_id', models.PositiveIntegerField(verbose_name='Rack ID')),
                ('retail_price', models.FloatField(verbose_name='Retail Price')),
                ('addresses', models.ManyToManyField(related_name='truckstops', to='addresses.Address', verbose_name='Addresses')),
            ],
            options={
                'verbose_name': 'Truckstop',
                'verbose_name_plural': 'Truckstops',
            },
        ),
    ]
